#Ventana de login
login.title = Iniciar Sesion
login.username = Usuario
login.password = Contraseña
login.button = Acceder
login.register = Registrate
login.tooltip = Introduce tu email
password.tooltip = Introduce tu contraseña
ntc= ¿No tienes una cuenta?