#Ventana de login
login.title = Iniciar Sesion
login.username = Usuario
login.password = Contraseña
login.button = Acceder
login.register = Registrate
login.tooltip = Introduce tu email
password.tooltip = Introduce tu contraseña
ntc= ¿No tienes una cuenta?

#Ventana registro
labelRegistro=Regístrate en UrbanDrive
labelCampos=Todos los campos son obligatorios
labelNombre=Nombre
labelEmail=Email
labelContraseña=Contraseña
labelNumero=Número de móvil
labelDNI=DNI
buttonUnirse=Regístrate
HlinicioSesion=Inicia Sesión
labelUsuario=¿Eres usuario?
