# Ventana de login
login.title=Iniciar Sesión
login.username=Usuario
login.password=Contraseña
login.button=Acceder
login.register=Regístrate
login.tooltip=Introduce tu email
password.tooltip=Introduce tu contraseña
ntc=¿No tienes una cuenta?

# Ventana de registro
labelRegistro=Regístrate en UrbanDrive
labelCampos=Todos los campos son obligatorios
labelNombre=Nombre
labelEmail=Email
labelContraseña=Contraseña
labelNumero=Número de móvil
labelDNI=DNI
buttonUnirse=Regístrate
HlinicioSesion=Inicia Sesión
labelUsuario=¿Eres usuario?

# Ventana de administración
welcome.text=¡Bienvenido, @!
tab.coches=Coches
tab.motos=Motos
tab.furgonetas=Furgonetas
button.paginaPrincipal=Página principal
button.gestionarVehiculos=Gestionar vehículos
button.mostrarVehiculos=Mostrar vehículos
button.anadir=Añadir
button.borrar=Borrar
button.modificar=Modificar
button.mostrar=Mostrar
label.id=Id
label.marca=Marca
label.modelo=Modelo
label.anio=Año
label.tipo=Tipo
label.precio=Precio

# Ventana de compra
label.detallesAlquiler=Detalles del Alquiler
col.marca=Marca
col.modelo=Modelo
col.tipo=Tipo
col.idCliente=Cliente ID
col.fechaInicio=Fecha Inicio
col.fechaFin=Fecha Fin
col.total=Total (?)
button.alquilar=Alquilar
button.volver=Volver

# Ventana de mis vehículos
label.resumenVehiculos=RESUMEN DE MIS VEHÍCULOS
col.idAlquiler=ID Alquiler
col.anio=Año
button.volverPrincipal=Volver a la pantalla principal

# Textos generales
button.misVehiculos=Mis vehículos
button.irCompra=Ir a la pantalla de compra
button.guardarFiltros=Guardar Filtros
label.fechaInicio=Fecha de inicio
label.fechaFin=Fecha de final
label.seleccionarFecha=Selecciona la fecha
combobox.marca=Marca
combobox.modelo=Modelo
combobox.anio=Año
combobox.tipo=Tipo
combobox.precio=Precio
table.id=Id
table.marca=Marca
table.modelo=Modelo
table.anio=Año
table.precio=Precio